[versions]
agp = "8.11.2"
jdwebview = "1.0.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
constraintlayout = "2.1.4"
materialVersion = "1.9.0"
navigationFragment = "2.6.0"
navigationUi = "2.6.0"
kotlin = "2.2.0"
coreKtx = "1.10.1"
router = "1.3.0"

[libraries]
jdbridge = { module = "com.github.JDFED.JDHybrid:JDBridge", version.ref = "jdwebview" }
jdwebview = { module = "com.github.JDFED.JDHybrid:JDWebView", version.ref = "jdwebview" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material-v190 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
router = { module = "cn.therouter:router", version.ref = "router" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

